version: "3"

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/myapp
    depends_on:
      - php

  app:
    build: .
    volumes:
      # ホストの./myappフォルダを同期
      - ./src:/var/www/html/src
